**Prepare data for machine learning**

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("diabetes.csv")
#view first 5 rows
df.head()

   6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [3]:
#Add labels
filename='diabetes.csv'
names=['preg','glu','bp','skin','insulin','bmi','pedi','age','class']
df=pd.read_csv(filename,names=names)
#view first 20 rows
df.head(20)

    preg  glu  bp  skin  insulin   bmi   pedi  age  class
0      6  148  72    35        0  33.6  0.627   50      1
1      1   85  66    29        0  26.6  0.351   31      0
2      8  183  64     0        0  23.3  0.672   32      1
3      1   89  66    23       94  28.1  0.167   21      0
4      0  137  40    35      168  43.1  2.288   33      1
5      5  116  74     0        0  25.6  0.201   30      0
6      3   78  50    32       88  31.0  0.248   26      1
7     10  115   0     0        0  35.3  0.134   29      0
8      2  197  70    45      543  30.5  0.158   53      1
9      8  125  96     0        0   0.0  0.232   54      1
10     4  110  92     0        0  37.6  0.191   30      0
11    10  168  74     0        0  38.0  0.537   34      1
12    10  139  80     0        0  27.1  1.441   57      0
13     1  189  60    23      846  30.1  0.398   59      1
14     5  166  72    19      175  25.8  0.587   51      1
15     7  100   0     0        0  30.0  0.484   32      1
16     0  118  84    47      230  45.8  0.551   31      1
17     7  107  74     0        0  29.6  0.254   31      1
18     1  103  30    38       83  43.3  0.183   33      0
19     1  115  70    30       96  34.6  0.529   32      1

The **drop()** method removes the specified row or column. By specifying the column axis ( axis='columns' ), the drop() method removes the specified column. By specifying the row axis ( axis='index' ), the drop() method removes the specified row.

What does **DF [' Col ']** unique () return?

DataFrame(). unique() method is used when we deal with a single column of a DataFrame and returns all unique elements of a column. The method returns a DataFrame containing the unique elements of a column, along with their corresponding index labels.

In [6]:
#separate input and output
X=df.drop('class',axis=True)
Y=df['class']

In [7]:
#view input features
X

     preg  glu  bp  skin  insulin   bmi   pedi  age
0       6  148  72    35        0  33.6  0.627   50
1       1   85  66    29        0  26.6  0.351   31
2       8  183  64     0        0  23.3  0.672   32
3       1   89  66    23       94  28.1  0.167   21
4       0  137  40    35      168  43.1  2.288   33
..    ...  ...  ..   ...      ...   ...    ...  ...
763    10  101  76    48      180  32.9  0.171   63
764     2  122  70    27        0  36.8  0.340   27
765     5  121  72    23      112  26.2  0.245   30
766     1  126  60     0        0  30.1  0.349   47
767     1   93  70    31        0  30.4  0.315   23

[768 rows x 8 columns]

In [8]:
#View output features
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: class, Length: 768, dtype: int64

**Rescale Data**

**MinMaxScaler**. Transform features by scaling each feature to a given range. This estimator scales and translates each feature individually such that it is in the given range on the training set, e.g. between zero and one.

What is **feature range** in MinMax scaler?

Therefore, it makes mean = 0 and scales the data to unit variance. MinMaxScaler scales all the data features in the range [0, 1] or else in the range [-1, 1] if there are negative values in the dataset.

What does scaler Fit_transform do?
**fit_transform()**

– It is used on the training data so that we can scale the training data and also learn the scaling parameters. Here, the model built will learn the mean and variance of the features of the training set. These learned parameters are then further used to scale our test data.

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
rescaledX=scaler.fit_transform(X)
rescaledX

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

Numpy's **set_printoptions**(~) method customizes how Numpy arrays are printed.

To display each entry in the array with precise digits of precision, call numpy. **set_printoptions** (precision=None, suppress=None). Set suppress to True to disable scientific notation when it is presented. NumPy uses up to 8 digits of precision by default, and scientific notation is not suppressed.

To display each entry in the array with **precise digits** of precision, call numpy. set_printoptions (precision=None, suppress=None). Set suppress to True to disable scientific notation when it is presented. NumPy uses up to 8 digits of precision by default, and scientific notation is not suppressed.

In [10]:
from numpy.core.arrayprint import set_printoptions
set_printoptions(precision=3)
rescaledX

array([[0.353, 0.744, 0.59 , ..., 0.501, 0.234, 0.483],
       [0.059, 0.427, 0.541, ..., 0.396, 0.117, 0.167],
       [0.471, 0.92 , 0.525, ..., 0.347, 0.254, 0.183],
       ...,
       [0.294, 0.608, 0.59 , ..., 0.39 , 0.071, 0.15 ],
       [0.059, 0.633, 0.492, ..., 0.449, 0.116, 0.433],
       [0.059, 0.467, 0.574, ..., 0.453, 0.101, 0.033]])

**Standardize Data**

**sklearn. preprocessing . StandardScaler**. Standardize features by removing the mean and scaling to unit variance.

**StandardScaler** removes the mean and scales each feature/variable to unit variance. This operation is performed feature-wise in an independent way. StandardScaler can be influenced by outliers (if they exist in the dataset) since it involves the estimation of the empirical mean and standard deviation of each feature.

In [11]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler().fit(X)
rescaledX=scaler.transform(X)
rescaledX

array([[ 0.64 ,  0.848,  0.15 , ...,  0.204,  0.468,  1.426],
       [-0.845, -1.123, -0.161, ..., -0.684, -0.365, -0.191],
       [ 1.234,  1.944, -0.264, ..., -1.103,  0.604, -0.106],
       ...,
       [ 0.343,  0.003,  0.15 , ..., -0.735, -0.685, -0.276],
       [-0.845,  0.16 , -0.471, ..., -0.24 , -0.371,  1.171],
       [-0.845, -0.873,  0.046, ..., -0.202, -0.474, -0.871]])

In [12]:
set_printoptions(precision=3)
rescaledX

array([[ 0.64 ,  0.848,  0.15 , ...,  0.204,  0.468,  1.426],
       [-0.845, -1.123, -0.161, ..., -0.684, -0.365, -0.191],
       [ 1.234,  1.944, -0.264, ..., -1.103,  0.604, -0.106],
       ...,
       [ 0.343,  0.003,  0.15 , ..., -0.735, -0.685, -0.276],
       [-0.845,  0.16 , -0.471, ..., -0.24 , -0.371,  1.171],
       [-0.845, -0.873,  0.046, ..., -0.202, -0.474, -0.871]])

**Normalize Data**

**Normalizer**. Normalize samples individually to unit norm. Each sample (i.e. each row of the data matrix) with at least one non zero component is rescaled independently of other samples so that its norm (l1, l2 or inf) equals one.

The data can be normalized by subtracting the mean (µ) of each feature and a division by the standard deviation (σ). This way, each feature has a mean of 0 and a standard deviation of 1. This results in faster convergence.

In [13]:
from sklearn.preprocessing import Normalizer
scaler=Normalizer().fit(X)
normalizedX=scaler.transform(X)
normalizedX

array([[0.034, 0.828, 0.403, ..., 0.188, 0.004, 0.28 ],
       [0.008, 0.716, 0.556, ..., 0.224, 0.003, 0.261],
       [0.04 , 0.924, 0.323, ..., 0.118, 0.003, 0.162],
       ...,
       [0.027, 0.651, 0.388, ..., 0.141, 0.001, 0.161],
       [0.007, 0.838, 0.399, ..., 0.2  , 0.002, 0.313],
       [0.008, 0.736, 0.554, ..., 0.241, 0.002, 0.182]])

In [14]:
set_printoptions(precision=3)
normalizedX

array([[0.034, 0.828, 0.403, ..., 0.188, 0.004, 0.28 ],
       [0.008, 0.716, 0.556, ..., 0.224, 0.003, 0.261],
       [0.04 , 0.924, 0.323, ..., 0.118, 0.003, 0.162],
       ...,
       [0.027, 0.651, 0.388, ..., 0.141, 0.001, 0.161],
       [0.007, 0.838, 0.399, ..., 0.2  , 0.002, 0.313],
       [0.008, 0.736, 0.554, ..., 0.241, 0.002, 0.182]])

**Binarize Data**

**Binarization** is the process of transforming data features of any entity into vectors of binary numbers to make classifier algorithms more efficient. In a simple example, transforming an image's gray-scale from the 0-255 spectrum to a 0-1 spectrum is binarization.

In [15]:
from sklearn.preprocessing import Binarizer
binarizer=Binarizer(threshold=0.0).fit(X)
binaryX=binarizer.transform(X)
binaryX

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])