# **One Hot Encoding**

One-hot encoding in machine learning is the conversion of categorical information into a format that may be fed into machine learning algorithms to improve prediction accuracy. One-hot encoding is a common method for dealing with categorical data in machine learning. 

The One Hot Encoding technique creates a number of additional features based on the number of unique values in the categorical feature. Every unique value in the category is added as a feature. Hence the One Hot Encoding is known as the process of creating dummy variables.

In [1]:
#Import library
import pandas as pd

In [2]:
#Load dataset
df=pd.read_csv('carprices.csv')
df

         Car Model  Mileage  Sell Price  Age
0           BMW X5    69000       18000    6
1           BMW X5    35000       34000    3
2           BMW X5    57000       26100    5
3           BMW X5    22500       40000    2
4           BMW X5    46000       31500    4
5             Audi    59000       29400    5
6             Audi    52000       32000    5
7             Audi    72000       19300    6
8             Audi    91000       12000    8
9   Mercedez Benz     67000       22000    6
10  Mercedez Benz     83000       20000    7
11  Mercedez Benz     79000       21000    7
12  Mercedez Benz     59000       33000    5
13          Toyota    51000       42000    4
14          Toyota    65000       32000    7
15          Toyota    39000       55000    5

In [3]:
#One Hot Encoding Implementation
dummies=pd.get_dummies(df['Car Model'])
dummies

    Audi  BMW X5  Mercedez Benz   Toyota
0      0       1               0       0
1      0       1               0       0
2      0       1               0       0
3      0       1               0       0
4      0       1               0       0
5      1       0               0       0
6      1       0               0       0
7      1       0               0       0
8      1       0               0       0
9      0       0               1       0
10     0       0               1       0
11     0       0               1       0
12     0       0               1       0
13     0       0               0       1
14     0       0               0       1
15     0       0               0       1

In [4]:
#Merging one hot encoded dummy dataset and main dataset
merged=pd.concat([df,dummies],axis='columns')
merged

,Car Model,Mileage,Sell Price,Age,Audi,BMW X5,Mercedez Benz,Toyota
0,BMW X5,69000,18000,6,0,1,0,0
1,BMW X5,35000,34000,3,0,1,0,0
2,BMW X5,57000,26100,5,0,1,0,0
3,BMW X5,22500,40000,2,0,1,0,0
4,BMW X5,46000,31500,4,0,1,0,0
5,Audi,59000,29400,5,1,0,0,0
6,Audi,52000,32000,5,1,0,0,0
7,Audi,72000,19300,6,1,0,0,0
8,Audi,91000,12000,8,1,0,0,0
9,Mercedez Benz,67000,22000,6,0,0,1,0
10,Mercedez Benz,83000,20000,7,0,0,1,0
11,Mercedez Benz,79000,21000,7,0,0,1,0
12,Mercedez Benz,59000,33000,5,0,0,1,0
13,Toyota,51000,42000,4,0,0,0,1
14,Toyota,65000,32000,7,0,0,0,1
15,Toyota,39000,55000,5,0,0,0,1

In [5]:
#Car Model needs to be removed as performing one hot encoding 
final=merged.drop(['Car Model'],axis='columns')
final

    Mileage  Sell Price  Age  Audi  BMW X5  Mercedez Benz   Toyota
0     69000       18000    6     0       1               0       0
1     35000       34000    3     0       1               0       0
2     57000       26100    5     0       1               0       0
3     22500       40000    2     0       1               0       0
4     46000       31500    4     0       1               0       0
5     59000       29400    5     1       0               0       0
6     52000       32000    5     1       0               0       0
7     72000       19300    6     1       0               0       0
8     91000       12000    8     1       0               0       0
9     67000       22000    6     0       0               1       0
10    83000       20000    7     0       0               1       0
11    79000       21000    7     0       0               1       0
12    59000       33000    5     0       0               1       0
13    51000       42000    4     0       0               0       1
14    65000       32000    7     0       0               0       1
15    39000       55000    5     0       0               0       1

In [6]:
#Separate the target output of Sell Price 
y=df['Sell Price']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
13    42000
14    32000
15    55000
Name: Sell Price, dtype: int64

In [7]:
#Separate the input features by dropping target output 
x=final.drop(['Sell Price'],axis=1)
x

    Mileage  Age  Audi  BMW X5  Mercedez Benz   Toyota
0     69000    6     0       1               0       0
1     35000    3     0       1               0       0
2     57000    5     0       1               0       0
3     22500    2     0       1               0       0
4     46000    4     0       1               0       0
5     59000    5     1       0               0       0
6     52000    5     1       0               0       0
7     72000    6     1       0               0       0
8     91000    8     1       0               0       0
9     67000    6     0       0               1       0
10    83000    7     0       0               1       0
11    79000    7     0       0               1       0
12    59000    5     0       0               1       0
13    51000    4     0       0               0       1
14    65000    7     0       0               0       1
15    39000    5     0       0               0       1

In [8]:
#Train the model 
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x,y)

LinearRegression()

In [9]:
#Determine the accuracy of the trained model
model.score(x,y)

0.9461669991799323

In [10]:
#Predict the Sell price by providing input features 
model.predict([[50000,5,0,1,0,0]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([28422.3014868])

# **Level Encoding**

Label Encoding refers to converting the labels into a numeric form so as to convert them into the machine-readable form. Machine learning algorithms can then decide in a better way how those labels must be operated. It is an important pre-processing step for the structured dataset in supervised learning.

In [12]:
# Import libraries 
import numpy as np
import pandas as pd
  
# Import dataset
df = pd.read_csv('carprices.csv')
  
df['Car Model'].unique()

array(['BMW X5', 'Audi', 'Mercedez Benz ', 'Toyota'], dtype=object)

In [13]:
# Import label encoder
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'Car Model'.
df['Car Model']= label_encoder.fit_transform(df['Car Model'])
  
df['Car Model'].unique()

array([1, 0, 2, 3])

In [14]:
df

    Car Model  Mileage  Sell Price  Age
0           1    69000       18000    6
1           1    35000       34000    3
2           1    57000       26100    5
3           1    22500       40000    2
4           1    46000       31500    4
5           0    59000       29400    5
6           0    52000       32000    5
7           0    72000       19300    6
8           0    91000       12000    8
9           2    67000       22000    6
10          2    83000       20000    7
11          2    79000       21000    7
12          2    59000       33000    5
13          3    51000       42000    4
14          3    65000       32000    7
15          3    39000       55000    5

In [15]:
#Separate the target output of Sell Price 
y=df['Sell Price']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
13    42000
14    32000
15    55000
Name: Sell Price, dtype: int64

In [17]:
#Separate the input features by dropping target output 
x=df.drop(['Sell Price'],axis=1)
x

    Car Model  Mileage  Age
0           1    69000    6
1           1    35000    3
2           1    57000    5
3           1    22500    2
4           1    46000    4
5           0    59000    5
6           0    52000    5
7           0    72000    6
8           0    91000    8
9           2    67000    6
10          2    83000    7
11          2    79000    7
12          2    59000    5
13          3    51000    4
14          3    65000    7
15          3    39000    5

In [18]:
#Train the model 
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x,y)

LinearRegression()

In [19]:
#Determine the accuracy of the trained model
model.score(x,y)

0.8568430959770131

**Limitation of label Encoding** : Label encoding converts the data in machine-readable form, but it assigns a unique number(starting from 0) to each class of data. This may lead to the generation of priority issues in the training of data sets. A label with a high value may be considered to have high priority than a label having a lower value.

Example: An attribute having output classes Mexico, Paris, Dubai. On Label Encoding, this column lets Mexico is replaced with 0, Paris is replaced with 1, and Dubai is replaced with 2. With this, it can be interpreted that Dubai has high priority than Mexico and Paris while training the model, But actually, there is no such priority relation between these cities here.