**Null value Handling**

In [1]:
#Importing libraries 
import pandas as pd
import numpy as np
from sklearn import linear_model
#loading dataset
df=pd.read_csv('car driving risk analysis multiple.csv')
df.head()

   speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         NaN    60
4    140        5         3.0    82

In [2]:
#View specific features
df.experience

0     5.0
1    13.0
2     4.0
3     NaN
4     3.0
5     8.0
Name: experience, dtype: float64

In [3]:
#Calculate mean value to replace the NaN value 
df.experience.mean()

6.6

In [4]:
#Or we can calculate median value to replace the NaN value 
df.experience.median()

5.0

In [5]:
#Create a variable to put the median value for replacing the NaN value
PreprocessedData=df.experience.median()
PreprocessedData

5.0

In [6]:
#replace the NaN value obtained in line 10
df.experience = df.experience.fillna(PreprocessedData)
df

   speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         5.0    60
4    140        5         3.0    82
5    115        2         8.0    10

In [7]:
df.experience

0     5.0
1    13.0
2     4.0
3     5.0
4     3.0
5     8.0
Name: experience, dtype: float64